# Generated by Django 3.0.8 on 2020-07-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BkId', models.AutoField(primary_key=True, serialize=False, verbose_name='Bkid')),
                ('BkTitle', models.CharField(max_length=15, verbose_name='BkTitle')),
                ('BkAuthor', models.CharField(max_length=15, verbose_name='BkAuthor')),
                ('BkPublisher', models.CharField(max_length=15, verbose_name='BkPublisher')),
                ('BkPubDate', models.CharField(max_length=8, verbose_name='BkPubDate')),
                ('Category', models.CharField(max_length=15, verbose_name='Category')),
                ('Popularity', models.IntegerField(default=0, verbose_name='Popularity')),
                ('Rating', models.FloatField(default=0, verbose_name='Reting')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False, verbose_name='UserId')),
                ('UserName', models.CharField(max_length=15, unique=True, verbose_name='UserName')),
                ('Password', models.CharField(max_length=15, verbose_name='Password')),
                ('CreateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False, verbose_name='ReviewId')),
                ('ReviewCont', models.TextField(verbose_name='ReviewCont')),
                ('ReviewDate', models.DateTimeField(auto_now_add=True, verbose_name='ReviewDate')),
                ('Poster', models.CharField(max_length=15, verbose_name='Poster')),
                ('BkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.Book')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.User')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_stars', models.FloatField(verbose_name='rating stars')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='post_time')),
                ('first_rate', models.CharField(max_length=7, null=True, verbose_name='first_rate')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.User')),
            ],
            options={
                'db_table': 'rating_record',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(max_length=7, verbose_name='create_time')),
                ('goal', models.IntegerField(default=0, verbose_name='goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.User')),
            ],
            options={
                'db_table': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('CoId', models.AutoField(primary_key=True, serialize=False, verbose_name='CoId')),
                ('CoName', models.CharField(max_length=15, verbose_name='CoName')),
                ('CoCreateDate', models.DateTimeField(auto_now_add=True)),
                ('CoUpdateDate', models.DateTimeField(auto_now=True)),
                ('CoOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.User')),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='CoBk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('read_dates', models.IntegerField(null=True, verbose_name='read_days')),
                ('status', models.CharField(max_length=15, null=True, verbose_name='status')),
                ('BkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.Book')),
                ('CoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.Collection')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP9900_LIM.User')),
            ],
            options={
                'db_table': 'CoBk',
            },
        ),
    ]
