# Generated by Django 3.0.8 on 2020-07-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP9900_LIM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Recommend_model',
            field=models.IntegerField(default=0, verbose_name='Recommend_model'),
        ),
    ]
