# Generated by Django 3.0.8 on 2020-07-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP9900_LIM', '0002_user_recommend_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Last_add',
            field=models.IntegerField(default=0, verbose_name='Last_add'),
        ),
    ]
